spring.application.name=opensearch-mcp

# Main application will be exposed at http://localhost:8080
server.port=8080

# Actuator endpoints will be exposed at http://localhost:8081/actuator
management.server.port=8081
management.endpoints.web.exposure.include=*
