spring:
  application:
    name: opensearch-mcp
  main:
    web-application-type: none
  ai:
    mcp:
      server:
        name: o8h-mcp-server
        stdio: true

opensearch:
  clusters:
    local:
      url: https://localhost:9200
      username: ${OPENSEARCH_USERNAME:admin}
      password: ${OPENSEARCH_PASSWORD:}
      ssl-verification-disabled: true
