spring:
  application:
    name: opensearch-mcp
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: o8h-mcp-server
        stdio: true

logging:
  level:
    root: INFO
    org.apache.tomcat.util.net.NioEndpoint: OFF

opensearch:
  write-enabled: true
