spring:
  application:
    name: opensearch-mcp
  ai:
    mcp:
      server:
        name: o8h-mcp-server
        protocol: STREAMABLE

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.apache.catalina.connector.ClientAbortException: OFF

opensearch:
  clusters:
    local:
      url: https://localhost:9200
      username: ${OPENSEARCH_USERNAME:admin}
      password: ${OPENSEARCH_PASSWORD:}
      ssl-verification-disabled: true
